sampleproject:
  outputs:
    dev:
      database: awsdatacatalog
      region_name: eu-west-1
      s3_data_dir: s3://bucket_name/prefix/
      s3_staging_dir: 's3://athena_query_result/prefix/'
      schema: sampledb
      threads: 4
      type: athena
  target: dev